name: sdui_server
description: Dart server that emits UI JSON for the SDUI client.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  sdui_models:
    path: ../sdui_models

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
